config/routes.rb
Rails.application.routes.draw do
  resources :powers
  resources :heros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hero.rb
class Hero < ApplicationRecord
end

app/models/power.rb
class Power < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: %i[ show edit update destroy ]

  # GET /heros or /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1 or /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros or /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to hero_url(@hero), notice: "Hero was successfully created." }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1 or /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to hero_url(@hero), notice: "Hero was successfully updated." }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1 or /heros/1.json
  def destroy
    @hero.destroy

    respond_to do |format|
      format.html { redirect_to heros_url, notice: "Hero was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hero_params
      params.fetch(:hero, {})
    end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  before_action :set_power, only: %i[ show edit update destroy ]

  # GET /powers or /powers.json
  def index
    @powers = Power.all
  end

  # GET /powers/1 or /powers/1.json
  def show
  end

  # GET /powers/new
  def new
    @power = Power.new
  end

  # GET /powers/1/edit
  def edit
  end

  # POST /powers or /powers.json
  def create
    @power = Power.new(power_params)

    respond_to do |format|
      if @power.save
        format.html { redirect_to power_url(@power), notice: "Power was successfully created." }
        format.json { render :show, status: :created, location: @power }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /powers/1 or /powers/1.json
  def update
    respond_to do |format|
      if @power.update(power_params)
        format.html { redirect_to power_url(@power), notice: "Power was successfully updated." }
        format.json { render :show, status: :ok, location: @power }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /powers/1 or /powers/1.json
  def destroy
    @power.destroy

    respond_to do |format|
      format.html { redirect_to powers_url, notice: "Power was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power
      @power = Power.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def power_params
      params.fetch(:power, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/views/heros/_form.html.erb
<%= form_with(model: hero) do |form| %>
  <% if hero.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
        <% hero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/heros/_hero.html.erb
<div id="<%= dom_id hero %>">
</div>

app/views/heros/edit.html.erb
<h1>Editing hero</h1>

<%= render "form", hero: @hero %>

<br>

<div>
  <%= link_to "Show this hero", @hero %> |
  <%= link_to "Back to heros", heros_path %>
</div>

app/views/heros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Heros</h1>

<div id="heros">
  <% @heros.each do |hero| %>
    <%= render hero %>
    <p>
      <%= link_to "Show this hero", hero %>
    </p>
  <% end %>
</div>

<%= link_to "New hero", new_hero_path %>

app/views/heros/new.html.erb
<h1>New hero</h1>

<%= render "form", hero: @hero %>

<br>

<div>
  <%= link_to "Back to heros", heros_path %>
</div>

app/views/heros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hero %>
<h1>
  <%=@hero.name %>
</h1>
<h1>
  <%=@hero.created_at %>
</h1>
<div>
  <%= link_to "Edit this hero", edit_hero_path(@hero) %> |
  <%= link_to "Back to heros", heros_path %>

  <%= button_to "Destroy this hero", @hero, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I love trains</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/powers/_form.html.erb
<%= form_with(model: power) do |form| %>
  <% if power.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(power.errors.count, "error") %> prohibited this power from being saved:</h2>

      <ul>
        <% power.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/powers/_power.html.erb
<div id="<%= dom_id power %>">
</div>

app/views/powers/edit.html.erb
<h1>Editing power</h1>

<%= render "form", power: @power %>

<br>

<div>
  <%= link_to "Show this power", @power %> |
  <%= link_to "Back to powers", powers_path %>
</div>

app/views/powers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Powers</h1>

<div id="powers">
  <% @powers.each do |power| %>
    <%= render power %>
    <p>
      <%= link_to "Show this power", power %>
    </p>
  <% end %>
</div>

<%= link_to "New power", new_power_path %>

app/views/powers/new.html.erb
<h1>New power</h1>

<%= render "form", power: @power %>

<br>

<div>
  <%= link_to "Back to powers", powers_path %>
</div>

app/views/powers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @power %>

<div>
  <%= link_to "Edit this power", edit_power_path(@power) %> |
  <%= link_to "Back to powers", powers_path %>

  <%= button_to "Destroy this power", @power, method: :delete %>
</div>